/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mensajes;

import java.awt.Color;
import java.awt.Container;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author samsung
 */
public class Mensaje extends javax.swing.JDialog {

    private int ancho;
    private Dimension dim;
    private String ruta = "/imagenes/";
    private JLabel jIcono;
    private JLabel jlmensaje;
    private FondoGris fondoGris;

    public Mensaje(java.awt.Frame parent, boolean modal, String mensaje, int tipo) {
        super(parent, modal);
        ancho = (int) super.getToolkit().getScreenSize().getWidth();
        setPreferredSize(getPreferredSize());
        setSize(getPreferredSize());
        setLocationRelativeTo(null);
        super.getContentPane().setBackground(new Color(0, 106, 193));

        fondoGris = new FondoGris();
        fondoGris.setVisible(true);

        if (tipo == 0) {
            ImageIcon errorIcon = new ImageIcon(getClass().getResource(ruta + "notification_error.png"));
            jIcono = new JLabel(errorIcon);
            jIcono.setBounds(400, 35, 128, 128);
            this.add(jIcono);
        } else if (tipo == 1) {
            ImageIcon alertIcon = new ImageIcon(getClass().getResource(ruta + "notification_alert.png"));
            jIcono = new JLabel(alertIcon);
            jIcono.setBounds(400, 35, 128, 128);
            this.add(jIcono);
        }else if (tipo == 2) {
            ImageIcon alertIcon = new ImageIcon(getClass().getResource(ruta + "notification_ok.png"));
            jIcono = new JLabel(alertIcon);
            jIcono.setBounds(400, 35, 128, 128);
            this.add(jIcono);
        }

        jlmensaje = new JLabel(mensaje);
        jlmensaje.setBounds(550, 70, 500, 25);
        jlmensaje.setForeground(Color.WHITE);
        jlmensaje.setFont(new Font("Segoe UI", Font.BOLD, 18));
        this.add(jlmensaje);

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Aceptar = new javax.swing.JPanel();
        jLabelAceptar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        Aceptar.setBackground(new java.awt.Color(0, 106, 193));
        Aceptar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AceptarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AceptarMouseExited(evt);
            }
        });

        jLabelAceptar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelAceptar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAceptar.setText("Aceptar");

        javax.swing.GroupLayout AceptarLayout = new javax.swing.GroupLayout(Aceptar);
        Aceptar.setLayout(AceptarLayout);
        AceptarLayout.setHorizontalGroup(
            AceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AceptarLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabelAceptar)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        AceptarLayout.setVerticalGroup(
            AceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AceptarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(570, Short.MAX_VALUE)
                .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(557, 557, 557))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(Aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceptarMouseEntered
        Aceptar.setBackground(new java.awt.Color(244, 244, 244));
        jLabelAceptar.setForeground(Color.black);
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        Aceptar.setBorder(BorderFactory.createLineBorder(Color.black));

    }//GEN-LAST:event_AceptarMouseEntered

    private void AceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceptarMouseExited
        Aceptar.setBackground(new java.awt.Color(0, 106, 193));
        jLabelAceptar.setForeground(Color.white);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        Aceptar.setBorder(BorderFactory.createLineBorder(Color.white));
    }//GEN-LAST:event_AceptarMouseExited

    private void AceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AceptarMouseClicked

        if (fondoGris.isVisible()) {
            fondoGris.dispose();
        }
        this.dispose();
    }//GEN-LAST:event_AceptarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mensaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Mensaje dialog = new Mensaje(new javax.swing.JFrame(), true, "", 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }

    @Override
    public final Dimension getPreferredSize() {
        return new Dimension(ancho, 210);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Aceptar;
    private javax.swing.JLabel jLabelAceptar;
    // End of variables declaration//GEN-END:variables
}
