/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import BaseDatos.conexion;
import java.awt.Color;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import mensajes.Mensaje;

/**
 *
 * @author perne
 */
public class Administracion extends javax.swing.JPanel {

    /**
     * Creates new form Administracion
     */
    Mensaje mensaje;
    private DefaultListModel modeloLista = new DefaultListModel();
    Connection con = new conexion().getCon();    

    public Administracion() {
        initComponents();
        llenarLista();
        super.setBounds(419, 75, 650, 590);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldID1 = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSolicitudes = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaRespuesta = new javax.swing.JTextArea();
        jPanelSeleccionar = new javax.swing.JPanel();
        jLabelSeleccionar = new javax.swing.JLabel();
        jComboBoxTipos = new javax.swing.JComboBox();
        jPanelPublicar = new javax.swing.JPanel();
        jLabelPublicar = new javax.swing.JLabel();
        jPanelCambiarTipo = new javax.swing.JPanel();
        jLabelTipo = new javax.swing.JLabel();
        jPanelEliminar = new javax.swing.JPanel();
        jLabeEliminar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIDCaso = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jTextFieldID1.setEditable(false);

        setBackground(new java.awt.Color(0, 106, 193));
        setPreferredSize(new java.awt.Dimension(672, 599));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Administración de solicitudes");

        jListSolicitudes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "No hay solicitudes." };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListSolicitudes.setToolTipText("");
        jScrollPane1.setViewportView(jListSolicitudes);

        jTextAreaRespuesta.setColumns(20);
        jTextAreaRespuesta.setRows(5);
        jScrollPane2.setViewportView(jTextAreaRespuesta);

        jPanelSeleccionar.setBackground(new java.awt.Color(0, 106, 193));
        jPanelSeleccionar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanelSeleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSeleccionarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelSeleccionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelSeleccionarMouseExited(evt);
            }
        });

        jLabelSeleccionar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelSeleccionar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSeleccionar.setText("Seleccionar");
        jLabelSeleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSeleccionarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelSeleccionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelSeleccionarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelSeleccionarLayout = new javax.swing.GroupLayout(jPanelSeleccionar);
        jPanelSeleccionar.setLayout(jPanelSeleccionarLayout);
        jPanelSeleccionarLayout.setHorizontalGroup(
            jPanelSeleccionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSeleccionarLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabelSeleccionar)
                .addContainerGap())
        );
        jPanelSeleccionarLayout.setVerticalGroup(
            jPanelSeleccionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSeleccionarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSeleccionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBoxTipos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBoxTipos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hardware", "Software", "Redes", "Sistema Operativo" }));
        jComboBoxTipos.setToolTipText("Tipo");
        jComboBoxTipos.setEnabled(false);

        jPanelPublicar.setBackground(new java.awt.Color(0, 106, 193));
        jPanelPublicar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanelPublicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelPublicarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelPublicarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelPublicarMouseExited(evt);
            }
        });

        jLabelPublicar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPublicar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPublicar.setText("Publicar");

        javax.swing.GroupLayout jPanelPublicarLayout = new javax.swing.GroupLayout(jPanelPublicar);
        jPanelPublicar.setLayout(jPanelPublicarLayout);
        jPanelPublicarLayout.setHorizontalGroup(
            jPanelPublicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPublicarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelPublicar)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelPublicarLayout.setVerticalGroup(
            jPanelPublicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPublicarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelPublicar)
                .addContainerGap())
        );

        jPanelCambiarTipo.setBackground(new java.awt.Color(0, 106, 193));
        jPanelCambiarTipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanelCambiarTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCambiarTipoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelCambiarTipoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelCambiarTipoMouseExited(evt);
            }
        });

        jLabelTipo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTipo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipo.setText("Cambiar tipo");

        javax.swing.GroupLayout jPanelCambiarTipoLayout = new javax.swing.GroupLayout(jPanelCambiarTipo);
        jPanelCambiarTipo.setLayout(jPanelCambiarTipoLayout);
        jPanelCambiarTipoLayout.setHorizontalGroup(
            jPanelCambiarTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCambiarTipoLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabelTipo)
                .addGap(23, 23, 23))
        );
        jPanelCambiarTipoLayout.setVerticalGroup(
            jPanelCambiarTipoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCambiarTipoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTipo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelEliminar.setBackground(new java.awt.Color(0, 106, 193));
        jPanelEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanelEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelEliminarMouseExited(evt);
            }
        });

        jLabeEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabeEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jLabeEliminar.setText("Eliminar");

        javax.swing.GroupLayout jPanelEliminarLayout = new javax.swing.GroupLayout(jPanelEliminar);
        jPanelEliminar.setLayout(jPanelEliminarLayout);
        jPanelEliminarLayout.setHorizontalGroup(
            jPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEliminarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabeEliminar)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanelEliminarLayout.setVerticalGroup(
            jPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEliminarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabeEliminar)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");

        jTextFieldID.setEditable(false);
        jTextFieldID.setText(" ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CASO");

        jTextFieldIDCaso.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabelTitulo))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(jPanelSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldIDCaso))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jComboBoxTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelCambiarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jPanelPublicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSeleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldIDCaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPublicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jComboBoxTipos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelCambiarTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelSeleccionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSeleccionarMouseEntered
        jPanelSeleccionar.setBackground(new java.awt.Color(244, 244, 244));
        jLabelSeleccionar.setForeground(Color.BLACK);
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanelSeleccionarMouseEntered

    private void jPanelSeleccionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSeleccionarMouseExited
        jPanelSeleccionar.setBackground(new java.awt.Color(0, 106, 193));
        jLabelSeleccionar.setForeground(Color.WHITE);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jPanelSeleccionarMouseExited

    private void jPanelEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEliminarMouseEntered
        jPanelEliminar.setBackground(new java.awt.Color(244, 244, 244));
        jLabeEliminar.setForeground(Color.BLACK);
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanelEliminarMouseEntered

    private void jPanelEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEliminarMouseExited
        jPanelEliminar.setBackground(new java.awt.Color(0, 106, 193));
        jLabeEliminar.setForeground(Color.WHITE);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jPanelEliminarMouseExited

    private void jPanelPublicarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPublicarMouseEntered
        jPanelPublicar.setBackground(new java.awt.Color(244, 244, 244));
        jLabelPublicar.setForeground(Color.BLACK);
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanelPublicarMouseEntered

    private void jPanelPublicarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPublicarMouseExited
        jPanelPublicar.setBackground(new java.awt.Color(0, 106, 193));
        jLabelPublicar.setForeground(Color.WHITE);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jPanelPublicarMouseExited

    private void jPanelCambiarTipoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCambiarTipoMouseEntered
        jPanelCambiarTipo.setBackground(new java.awt.Color(244, 244, 244));
        jLabelTipo.setForeground(Color.BLACK);
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanelCambiarTipoMouseEntered

    private void jPanelCambiarTipoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCambiarTipoMouseExited
        jPanelCambiarTipo.setBackground(new java.awt.Color(0, 106, 193));
        jLabelTipo.setForeground(Color.WHITE);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jPanelCambiarTipoMouseExited

    private void jLabelSeleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSeleccionarMouseClicked
        MostrarSoluciones();
        
    }//GEN-LAST:event_jLabelSeleccionarMouseClicked

    private void jPanelSeleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSeleccionarMouseClicked
        MostrarSoluciones();
        
    }//GEN-LAST:event_jPanelSeleccionarMouseClicked

    private void jPanelEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEliminarMouseClicked
                        
        if(jTextFieldIDCaso.getText().equals("")){
            mensaje = new Mensaje((JFrame) getRootPane().getParent(), true, "Selecciona un caso antes de eliminarlo", 1);
            mensaje.setVisible(true);
        }else{
            int idCaso = Integer.parseInt(jTextFieldID.getText());
            EliminarCaso(idCaso);
        }
                
    }//GEN-LAST:event_jPanelEliminarMouseClicked

    private void jPanelPublicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPublicarMouseClicked
        String Respuesta = jTextAreaRespuesta.getText();
        
        if (!Respuesta.isEmpty()){
        InsertarEnTabla(jTextFieldIDCaso.getText(), jTextAreaRespuesta.getText(), (String) jComboBoxTipos.getSelectedItem());
        } else {
            mensaje = new Mensaje((JFrame) getRootPane().getParent(), true, "Debes ingresar una respuesta", 0);
            mensaje.setVisible(true);
        }
    }//GEN-LAST:event_jPanelPublicarMouseClicked

    private void jPanelCambiarTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCambiarTipoMouseClicked
        if (!jComboBoxTipos.isEnabled()) {
            jComboBoxTipos.setEnabled(true);
        }
    }//GEN-LAST:event_jPanelCambiarTipoMouseClicked

    private void jLabelSeleccionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSeleccionarMouseEntered
        jPanelSeleccionarMouseEntered(evt);
    }//GEN-LAST:event_jLabelSeleccionarMouseEntered

    private void jLabelSeleccionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSeleccionarMouseExited
        jPanelSeleccionarMouseExited(evt);
    }//GEN-LAST:event_jLabelSeleccionarMouseExited

    public void llenarLista() {
        try {
            PreparedStatement ps = con.prepareStatement("SELECT * FROM TBLSOLICITUD_CASOS");
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                modeloLista.addElement("ID: " + rs.getString(1) + " " + "CASO: " + rs.getString(2) + " ");
                jListSolicitudes.setModel(modeloLista);
                if (rs.getString(3) == "Hardware") {
                } else if (rs.getString(3) == "Software") {
                } else if (rs.getString(3) == "Redes") {
                } else if (rs.getString(3) == "Sistema Operativo") {
                }
            }
            con.commit();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void MostrarSoluciones() {
        try {
            PreparedStatement ps = con.prepareStatement("SELECT * FROM TBLSOLICITUD_CASOS");
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                if (rs.getRow() == jListSolicitudes.getSelectedIndex() + 1) {

                    jTextFieldID.setText(rs.getString(1));
                    jTextFieldIDCaso.setText(rs.getString(2));
                    jComboBoxTipos.setSelectedItem(rs.getString(3));

                }
            }
            con.commit();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void EliminarCaso(int id_caso) {
        try {
            PreparedStatement ps = con.prepareStatement("DELETE FROM TBLSOLICITUD_CASOS WHERE ID=" + id_caso);
            ResultSet rse = ps.executeQuery();

            int Seleccion = jListSolicitudes.getSelectedIndex();            
            
            if (rse.getRow() == jListSolicitudes.getSelectedIndex() + 1 || jListSolicitudes.getSelectedIndex() == 0) {
                modeloLista.removeElementAt(Seleccion);
                jListSolicitudes.setModel(modeloLista);
            }

        } catch (Exception e2) {
            e2.printStackTrace();
        }

    }

    public void InsertarEnTabla(String caso, String solucion, String tipo) {
        try {
            if (tipo.equals("Hardware")) {
                PreparedStatement ps = con.prepareStatement("INSERT INTO TBLCASOS_HW (ID,CASO,SOLUCION) VALUES \n"
                        + "        (incremental_so.nextval,'" + caso + "', '" + solucion + "')");
                ResultSet rs = ps.executeQuery();
            } else if (tipo.equals("Software")) {
                PreparedStatement ps = con.prepareStatement("INSERT INTO TBLCASOS_SW (ID,CASO,SOLUCION) VALUES \n"
                        + "        (incremental_so.nextval,'" + caso + "', '" + solucion + "')");
                ResultSet rs = ps.executeQuery();
            } else if (tipo.equals("Redes")) {
                PreparedStatement ps = con.prepareStatement("INSERT INTO TBLCASOS_RDS (ID,CASO,SOLUCION) VALUES \n"
                        + "        (incremental_so.nextval,'" + caso + "', '" + solucion + "')");
                ResultSet rs = ps.executeQuery();
            } else if (tipo.equals("Sistema Operativo")) {
                PreparedStatement ps = con.prepareStatement("INSERT INTO TBLCASOS_SO (ID,CASO,SOLUCION) VALUES \n"
                        + "        (incremental_so.nextval,'" + caso + "', '" + solucion + "')");

                ResultSet rs = ps.executeQuery();

            } else {
                JOptionPane.showMessageDialog(null, "Hubo un error en el envío de la solución, porfavor vuelve a intentarlo", "Error", JOptionPane.ERROR_MESSAGE);
            }

            EliminarCaso(Integer.parseInt(jTextFieldID.getText()));
            
            mensaje = new Mensaje((JFrame) getRootPane().getParent(), true, "¡Solución de solicitud guardada!", 2);
            mensaje.setVisible(true);      
            /*JOptionPane.showMessageDialog(null, "¡Solución de solicitud guardada!", "Solución enviada", JOptionPane.INFORMATION_MESSAGE);
            */
                con.commit();
        } catch (Exception e) {
            mensaje = new Mensaje((JFrame) getRootPane().getParent(), true, "Hubo un error en el envío de la solución, por favor vuelve a intentarlo", 0);
            mensaje.setVisible(true);
            System.out.println(e.getMessage());
            /*System.out.println(e.getMessage());
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Hubo un error en el envío de la solución, porfavor vuelve a intentarlo", "Error", JOptionPane.ERROR_MESSAGE);
                    */
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxTipos;
    private javax.swing.JLabel jLabeEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPublicar;
    private javax.swing.JLabel jLabelSeleccionar;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JList jListSolicitudes;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelCambiarTipo;
    private javax.swing.JPanel jPanelEliminar;
    private javax.swing.JPanel jPanelPublicar;
    private javax.swing.JPanel jPanelSeleccionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaRespuesta;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldID1;
    private javax.swing.JTextField jTextFieldIDCaso;
    // End of variables declaration//GEN-END:variables
}
