/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import BaseDatos.conexion;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.io.*;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author perne
 */
public class Usuarios extends javax.swing.JPanel {

    /**
     * Creates new form Administracion
     */
    DefaultTableModel modeloLista;
    Connection con = new conexion().getCon();
    int Seleccion = -1;

    public Usuarios() {

        modeloLista = new DefaultTableModel(null, getColumnas());
        llenarTabla();
        super.setBounds(419, 75, 650, 590);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldID1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jPanelGuardar = new javax.swing.JPanel();
        jLabelGuardar = new javax.swing.JLabel();
        jPanelBuscar = new javax.swing.JPanel();
        jLabelBuscar = new javax.swing.JLabel();
        jPanelActualizar = new javax.swing.JPanel();
        jLabelActualizar = new javax.swing.JLabel();
        jPanelEliminar = new javax.swing.JPanel();
        jLabeEliminar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldEstado = new javax.swing.JTextField();
        jPanelSalir = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelAtras = new javax.swing.JPanel();
        jLabelAtras = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jPasswordFieldclave = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        jComboBoxPerfil = new javax.swing.JComboBox();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jTextFieldID1.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID");

        setBackground(new java.awt.Color(0, 106, 193));
        setPreferredSize(new java.awt.Dimension(672, 599));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Registro de usuarios");

        jPanelGuardar.setBackground(new java.awt.Color(0, 106, 193));
        jPanelGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelGuardarMouseExited(evt);
            }
        });

        jLabelGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGuardar.setText("Guardar");
        jLabelGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelGuardarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelGuardarLayout = new javax.swing.GroupLayout(jPanelGuardar);
        jPanelGuardar.setLayout(jPanelGuardarLayout);
        jPanelGuardarLayout.setHorizontalGroup(
            jPanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGuardar)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelGuardarLayout.setVerticalGroup(
            jPanelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGuardarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelGuardar)
                .addContainerGap())
        );

        jPanelBuscar.setBackground(new java.awt.Color(0, 106, 193));
        jPanelBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBuscarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelBuscarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelBuscarMouseEntered(evt);
            }
        });

        jLabelBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBuscar.setText("Buscar");

        javax.swing.GroupLayout jPanelBuscarLayout = new javax.swing.GroupLayout(jPanelBuscar);
        jPanelBuscar.setLayout(jPanelBuscarLayout);
        jPanelBuscarLayout.setHorizontalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBuscarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabelBuscar)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanelBuscarLayout.setVerticalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelBuscar)
                .addContainerGap())
        );

        jPanelActualizar.setBackground(new java.awt.Color(0, 106, 193));
        jPanelActualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanelActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelActualizarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelActualizarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelActualizarMouseEntered(evt);
            }
        });

        jLabelActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelActualizar.setText("Actualizar");

        javax.swing.GroupLayout jPanelActualizarLayout = new javax.swing.GroupLayout(jPanelActualizar);
        jPanelActualizar.setLayout(jPanelActualizarLayout);
        jPanelActualizarLayout.setHorizontalGroup(
            jPanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelActualizarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelActualizar)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanelActualizarLayout.setVerticalGroup(
            jPanelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelActualizarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelActualizar)
                .addContainerGap())
        );

        jPanelEliminar.setBackground(new java.awt.Color(0, 106, 193));
        jPanelEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanelEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelEliminarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelEliminarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelEliminarMouseEntered(evt);
            }
        });

        jLabeEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabeEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jLabeEliminar.setText("Eliminar");

        javax.swing.GroupLayout jPanelEliminarLayout = new javax.swing.GroupLayout(jPanelEliminar);
        jPanelEliminar.setLayout(jPanelEliminarLayout);
        jPanelEliminarLayout.setHorizontalGroup(
            jPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEliminarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabeEliminar)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanelEliminarLayout.setVerticalGroup(
            jPanelEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEliminarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabeEliminar)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Estado");

        jPanelSalir.setBackground(new java.awt.Color(0, 106, 193));
        jPanelSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSalirMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("x");

        javax.swing.GroupLayout jPanelSalirLayout = new javax.swing.GroupLayout(jPanelSalir);
        jPanelSalir.setLayout(jPanelSalirLayout);
        jPanelSalirLayout.setHorizontalGroup(
            jPanelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSalirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
        );
        jPanelSalirLayout.setVerticalGroup(
            jPanelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSalirLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelAtras.setBackground(new java.awt.Color(0, 106, 193));
        jPanelAtras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanelAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAtrasMouseClicked(evt);
            }
        });

        jLabelAtras.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelAtras.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAtras.setText("Atras");

        javax.swing.GroupLayout jPanelAtrasLayout = new javax.swing.GroupLayout(jPanelAtras);
        jPanelAtras.setLayout(jPanelAtrasLayout);
        jPanelAtrasLayout.setHorizontalGroup(
            jPanelAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelAtrasLayout.setVerticalGroup(
            jPanelAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAtrasLayout.createSequentialGroup()
                .addComponent(jLabelAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });

        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Usuario");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Clave");

        jTableUsuarios.setModel(modeloLista);
        jScrollPane2.setViewportView(jTableUsuarios);

        jComboBoxPerfil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Soporte", "Invitado"}));
        jComboBoxPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabelTitulo)
                        .addGap(108, 108, 108)
                        .addComponent(jPanelAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldUsuario)
                            .addComponent(jTextFieldNombre)
                            .addComponent(jPasswordFieldclave, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(jTextFieldEstado))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jPanelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBoxPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitulo))
                    .addComponent(jPanelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 157, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGuardarMouseEntered
        jPanelGuardar.setBackground(new java.awt.Color(244, 244, 244));
        jLabelGuardar.setForeground(Color.BLACK);
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanelGuardarMouseEntered

    private void jPanelGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGuardarMouseExited
        jPanelGuardar.setBackground(new java.awt.Color(0, 106, 193));
        jLabelGuardar.setForeground(Color.WHITE);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jPanelGuardarMouseExited

    private void jPanelEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEliminarMouseEntered
        jPanelEliminar.setBackground(new java.awt.Color(244, 244, 244));
        jLabeEliminar.setForeground(Color.BLACK);
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanelEliminarMouseEntered

    private void jPanelEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEliminarMouseExited
        jPanelEliminar.setBackground(new java.awt.Color(0, 106, 193));
        jLabeEliminar.setForeground(Color.WHITE);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jPanelEliminarMouseExited

    private void jPanelBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBuscarMouseEntered
        jPanelBuscar.setBackground(new java.awt.Color(244, 244, 244));
        jLabelBuscar.setForeground(Color.BLACK);
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanelBuscarMouseEntered

    private void jPanelBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBuscarMouseExited
        jPanelBuscar.setBackground(new java.awt.Color(0, 106, 193));
        jLabelBuscar.setForeground(Color.WHITE);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jPanelBuscarMouseExited

    private void jPanelActualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelActualizarMouseEntered
        jPanelActualizar.setBackground(new java.awt.Color(244, 244, 244));
        jLabelActualizar.setForeground(Color.BLACK);
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanelActualizarMouseEntered

    private void jPanelActualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelActualizarMouseExited
        jPanelActualizar.setBackground(new java.awt.Color(0, 106, 193));
        jLabelActualizar.setForeground(Color.WHITE);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jPanelActualizarMouseExited

    private void jLabelGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGuardarMouseClicked
    String usuario = jTextFieldUsuario.getText();
    String nombre = jTextFieldNombre.getText();
    String psw = jPasswordFieldclave.getText();

    if (usuario.length() == 0) {
            JOptionPane.showMessageDialog(null, "Campo de usuario vacío", "Error",0);
        } else {
        int limite = 8;
        if(usuario.length()>=limite){
            evt.consume();
            if (nombre.length() == 0) {
                    JOptionPane.showMessageDialog(null, "Campo de nombre vacío ", "Error", 0);
                } else {
                    if (psw.length() == 0) {
                        JOptionPane.showMessageDialog(null, "Campo de clave vacía", "Error", 0);
                    } else {
                        if(psw.length()>=limite){
                            evt.consume();
                            if(nombre.equals(psw)){
                                JOptionPane.showMessageDialog(null, "La clave no puede ser el nombre", "Error", 0);
                            } else {
                            Guardar(jTextFieldUsuario.getText(), jTextFieldNombre.getText(), jPasswordFieldclave.getText(), (String) jComboBoxPerfil.getSelectedItem());
                            jTextFieldEstado.setText("");
                            jTextFieldID1.setText("");
                            jTextFieldNombre.setText("");
                            jTextFieldUsuario.setText("");
                            jPasswordFieldclave.setText("");
                            }
                        } else{                       
                            JOptionPane.showMessageDialog(null, "La clave debe contener mínimo 8 caracteres", "Error", 0);
                        }
                    }                             
                }
        } else {
            JOptionPane.showMessageDialog(null, "El usuario debe contener mínimo 8 caracteres", "Error", 0);     
        }
    }   
    }//GEN-LAST:event_jLabelGuardarMouseClicked

    private void jPanelGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelGuardarMouseClicked
    String usuario = jTextFieldUsuario.getText();
    String nombre = jTextFieldNombre.getText();
    String psw = jPasswordFieldclave.getText();

    if (usuario.length() == 0) {
            JOptionPane.showMessageDialog(null, "Campo de usuario vacío", "Error",0);
        } else {
        int limite = 8;
        if(usuario.length()>=limite){
            evt.consume();
            if (nombre.length() == 0) {
                    JOptionPane.showMessageDialog(null, "Campo de nombre vacío ", "Error", 0);
                } else {
                    if (psw.length() == 0) {
                        JOptionPane.showMessageDialog(null, "Campo de clave vacía", "Error", 0);
                    } else {
                        if(psw.length()>=limite){
                            evt.consume();
                            if(nombre.equals(psw)){
                                JOptionPane.showMessageDialog(null, "La clave no puede ser el nombre", "Error", 0);
                            } else {
                            Guardar(jTextFieldUsuario.getText(), jTextFieldNombre.getText(), jPasswordFieldclave.getText(), (String) jComboBoxPerfil.getSelectedItem());
                            jTextFieldEstado.setText("");
                            jTextFieldID1.setText("");
                            jTextFieldNombre.setText("");
                            jTextFieldUsuario.setText("");
                            jPasswordFieldclave.setText("");
                            }
                        } else{                       
                            JOptionPane.showMessageDialog(null, "La clave debe contener mínimo 8 caracteres", "Error", 0);
                        }
                    }                             
                }
        } else {
            JOptionPane.showMessageDialog(null, "El usuario debe contener mínimo 8 caracteres", "Error", 0);     
        }
    } 
        //Guardar(jTextFieldUsuario.getText(), jTextFieldNombre.getText(), jPasswordFieldclave.getText(), (String) jComboBoxPerfil.getSelectedItem());
    }//GEN-LAST:event_jPanelGuardarMouseClicked

    private void jPanelEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEliminarMouseClicked
        // TODO add your handling code here:
        Eliminar(jTextFieldUsuario.getText());
    }//GEN-LAST:event_jPanelEliminarMouseClicked

    private void jPanelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jPanelSalirMouseClicked

    private void jPanelBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBuscarMouseClicked
        Buscar(jTextFieldUsuario.getText());
    }//GEN-LAST:event_jPanelBuscarMouseClicked

    private void jPanelAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAtrasMouseClicked
        // TODO add your handling code here:     
    }//GEN-LAST:event_jPanelAtrasMouseClicked

    private void jPanelActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelActualizarMouseClicked
        Actualizar(jTextFieldUsuario.getText(), jTextFieldNombre.getText(), jPasswordFieldclave.getText(), jTextFieldEstado.getText(), (String) jComboBoxPerfil.getSelectedItem());
    }//GEN-LAST:event_jPanelActualizarMouseClicked

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jComboBoxPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPerfilActionPerformed

    private void jLabelGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGuardarMouseEntered
        jPanelGuardar.setBackground(new java.awt.Color(244, 244, 244));
        jLabelGuardar.setForeground(Color.BLACK);
        setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabelGuardarMouseEntered

    private void jLabelGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelGuardarMouseExited
        jPanelGuardar.setBackground(new java.awt.Color(0, 106, 193));
        jLabelGuardar.setForeground(Color.WHITE);
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabelGuardarMouseExited

    private void jTextFieldNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyReleased

    }//GEN-LAST:event_jTextFieldNombreKeyReleased

    private void jTextFieldNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyTyped
        int k = (int) evt.getKeyChar();
        if (k > 47 && k < 58) {
            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
            JOptionPane.showMessageDialog(null, "No puede ingresar numeros!!!", "Ventana Error Datos", JOptionPane.ERROR_MESSAGE);
        }
        if (k == 10) {
            jTextFieldNombre.transferFocus();
        }
    }//GEN-LAST:event_jTextFieldNombreKeyTyped

    public void Guardar(String usuario, String nombre, String clave, String perfil) {
        try {
            if (usuario != "q") {

                PreparedStatement ps = con.prepareStatement("INSERT INTO TBLUSUARIO (usuario,nombre, clave, estado, perfil) VALUES \n"
                        + "        ('" + usuario + "','" + nombre + "', '" + clave + "', 'activo','" + perfil + "')");
                ResultSet rs = ps.executeQuery();
            } else {
                JOptionPane.showMessageDialog(null, "Hubo un error en el envío de los datos, porfavor vuelve a intentarlo", "Error", JOptionPane.ERROR_MESSAGE);
            }

            JOptionPane.showMessageDialog(null, "¡Usuario guardado!", "Usuario guardado", JOptionPane.INFORMATION_MESSAGE);
            vaciarTabla();
            llenarTabla();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Hubo un error en el envío de los datos, porfavor vuelve a intentarlo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void Actualizar(String usuario, String nombre, String clave, String estado, String perfil) {
        /* "update tblusuario set nombre=?, clave=?, perfil=?, email=?, estado=? ,genero=? "
         + "  where usuario=?";*/
        try {
            if (usuario != "q") {

                PreparedStatement ps = con.prepareStatement("update tblusuario set nombre='" + nombre + "', clave='" + clave + "',"
                        + " estado='" + estado + "', perfil='" + perfil + "'  where usuario='" + usuario + "'");
                ResultSet rs = ps.executeQuery();
            } else {
                JOptionPane.showMessageDialog(null, "Hubo un error en el envío de los datos, porfavor vuelve a intentarlo", "Error", JOptionPane.ERROR_MESSAGE);
            }

            JOptionPane.showMessageDialog(null, "¡Usuario Actualizado!", "Usuario Actualizado", JOptionPane.INFORMATION_MESSAGE);
            vaciarTabla();
            llenarTabla();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Hubo un error en el envío de los datos, porfavor vuelve a intentarlo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//fin actualizar dato

    public void Eliminar(String usuario) {
        try {
            if (usuario != "q") {

                PreparedStatement ps = con.prepareStatement("DELETE FROM TBLUSUARIO WHERE USUARIO='" + usuario + "'");;
                ResultSet rs = ps.executeQuery();
            } else {
                JOptionPane.showMessageDialog(null, "Hubo un error , porfavor vuelve a intentarlo", "Error", JOptionPane.ERROR_MESSAGE);
            }

            JOptionPane.showMessageDialog(null, "¡Usuario Eliminado!", "Usuario Eliminado", JOptionPane.INFORMATION_MESSAGE);
            vaciarTabla();
            llenarTabla();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Hubo un error en el envío de los datos, porfavor vuelve a intentarlo", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    public void Buscar(String usuario) {
        try {
            if (usuario != "q") {

                PreparedStatement ps = con.prepareStatement("SELECT * FROM TBLUSUARIO WHERE USUARIO='" + usuario + "'");;
                ResultSet rs = ps.executeQuery();
                String cadena[] = new String[5];

                while (rs.next()) {
                    cadena = new String[5];
                    for (int x = 0; x < 5; ++x) {
                        cadena[x] = rs.getObject(x + 1).toString();
                    }
                }
                llenarCampos(cadena[0],cadena[1],cadena[2],cadena[3]);
            } else {
                JOptionPane.showMessageDialog(null, "Hubo un error , porfavor vuelve a intentarlo", "Error", JOptionPane.ERROR_MESSAGE);
            }

            JOptionPane.showMessageDialog(null, "¡Usuario Encontrado!", "Usuario Encontrado", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Hubo un error en el envío de los datos, porfavor vuelve a intentarlo", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    public void llenarTabla() {
        try {
            PreparedStatement ps = con.prepareStatement("SELECT * FROM TBLUSUARIO");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Object[] fila = new Object[5];//Creamos un Objeto con tantos parámetros como datos retorne cada fila 
                // de la consulta

                for (int i = 0; i < 5; i++) {
                    fila[i] = rs.getObject(i + 1);
                }

                modeloLista.addRow(fila); // Añade una fila al final del modelo de la tabla
            }

        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    private String[] getColumnas() {
        String columna[] = new String[]{"usuario", "nombre", "clave", "estado", " perfil"};
        return columna;
    }

    public void vaciarTabla() {
        while (modeloLista.getRowCount() > 0) {
            modeloLista.removeRow(0);
        }
    }

    public void llenarCampos(String usuario, String nombre, String estado, String perfil) {
        int i = 0;
        jTextFieldUsuario.setText(usuario);
        jTextFieldNombre.setText(nombre);
        jTextFieldEstado.setText(estado);

        if (perfil == "Administrador") {
            i = 0;
        } else if (perfil == "Soporte") {
            i = 1;
        } else if (perfil == "Invitado") {
            i = 2;
        }

        jComboBoxPerfil.setSelectedIndex(i);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxPerfil;
    private javax.swing.JLabel jLabeEliminar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelActualizar;
    private javax.swing.JLabel jLabelAtras;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JLabel jLabelGuardar;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelActualizar;
    private javax.swing.JPanel jPanelAtras;
    private javax.swing.JPanel jPanelBuscar;
    private javax.swing.JPanel jPanelEliminar;
    private javax.swing.JPanel jPanelGuardar;
    private javax.swing.JPanel jPanelSalir;
    private javax.swing.JPasswordField jPasswordFieldclave;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableUsuarios;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldID1;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
